version: 2
before:
  hooks:
    - go mod download
builds:
  - binary: avc-sync
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
universal_binaries:
  - replace: true
    hooks:
      post: make release-pkg BINARY_PATH="{{.Path}}" VERSION="{{.Version}}"
checksum:
  name_template: checksums.txt
  extra_files:
    - glob: "./dist/avc-sync*.pkg"
snapshot:
  version_template: "{{.Tag}}-{{.ShortCommit}}"
release:
  github:
    owner: szechyjs
    name: avc-sync
  prerelease: auto
  extra_files:
    - glob: dist/*.pkg
changelog:
  use: github-native
